baseurl      = "https://jamessann.netlify.app/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng-james"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linked
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"


  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Enable HTML in Markdown pages
  [markup]
    defaultMarkdownHandler = "goldmark"
    
    [markup.goldmark]
      [markup.goldmark.renderer]
        hardWraps = false
        unsafe = true
        xhtml = false

# Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"
    
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "James Sann"
    subtitle = "Principal Designer"
    keywords = "Product Designer, Creative Direction, Visual Designer, Design Leadership"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "James Sann. Principal Designer."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu

  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
    weight     = 2

  # [[menu.main]]
  #   identifier = "recommended"
  #   name       = "Recommended"
  #   url        = "/recommended"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 3